langauge: python
sudo: false
addons:
  postgresql: '11.8'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
python:
  - 3.7
  - 3.8
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 ./
  - ENV_STAGE=testing coverage run manage.py test tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
