version: "3"

services:
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hyperlog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - hyperlog_db_shared

  web:
    restart: always
    env_file: .env
    build: .
    command: bash dev.sh
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - hyperlog_db_shared

networks:
  hyperlog_db_shared:
